// ==============================================================================
// INDOSTATES HOSPITAL: ENTERPRISE ROLE-BASED ACCESS CONTROL (RBAC) CONFIGURATION
// Strict least-privilege permissions matrix for all 22 hospital roles
// ==============================================================================

import { UserRole, Permission } from "@/types/hms";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: [
    "appointment.read",
    "appointment.create",
    "appointment.update",
    "appointment.cancel",
    "appointment.checkin",
    "patient.read",
    "patient.update",
    "clinical.read",
    "clinical.write",
    "prescription.read",
    "prescription.write",
    "prescription.dispense",
    "lab.read",
    "lab.write",
    "lab.verify",
    "imaging.read",
    "imaging.write",
    "imaging.verify",
    "pharmacy.stock",
    "pharmacy.purchase",
    "billing.read",
    "billing.write",
    "finance.refund",
    "finance.reconcile",
    "ipd.read",
    "ipd.write",
    "ipd.discharge",
    "bed.manage",
    "emergency.read",
    "emergency.triage",
    "emergency.write",
    "ambulance.read",
    "ambulance.dispatch",
    "housekeeping.manage",
    "housekeeping.complete",
    "maintenance.manage",
    "maintenance.resolve",
    "caregiver.consent",
    "staff.manage",
    "doctor.manage",
    "department.manage",
    "audit.read",
    "system.manage",
    "queue.manage",
    "nurse.manage",
    "security.manage",
  ],
  HOSPITAL_ADMIN: [
    "appointment.read",
    "appointment.create",
    "appointment.update",
    "appointment.cancel",
    "appointment.checkin",
    "patient.read",
    "patient.update",
    "clinical.read",
    "prescription.read",
    "lab.read",
    "imaging.read",
    "billing.read",
    "billing.write",
    "finance.reconcile",
    "ipd.read",
    "ipd.write",
    "bed.manage",
    "emergency.read",
    "ambulance.read",
    "housekeeping.manage",
    "maintenance.manage",
    "staff.manage",
    "doctor.manage",
    "department.manage",
    "audit.read",
    "queue.manage",
    "nurse.manage",
    "security.manage",
  ],
  MEDICAL_DIRECTOR: [
    "appointment.read",
    "patient.read",
    "clinical.read",
    "clinical.write",
    "prescription.read",
    "lab.read",
    "lab.verify",
    "imaging.read",
    "imaging.verify",
    "ipd.read",
    "ipd.discharge",
    "emergency.read",
    "emergency.triage",
    "doctor.manage",
    "department.manage",
    "audit.read",
    "queue.manage",
  ],
  OPERATIONS_MANAGER: [
    "appointment.read",
    "appointment.create",
    "appointment.update",
    "appointment.cancel",
    "appointment.checkin",
    "patient.read",
    "queue.manage",
    "bed.manage",
    "ipd.read",
    "emergency.read",
    "ambulance.read",
    "ambulance.dispatch",
    "housekeeping.manage",
    "maintenance.manage",
    "billing.read",
    "department.manage",
    "audit.read",
  ],
  HR_MANAGER: [
    "staff.manage",
    "doctor.manage",
    "department.manage",
    "audit.read",
  ],
  DEPARTMENT_HEAD: [
    "appointment.read",
    "patient.read",
    "clinical.read",
    "clinical.write",
    "prescription.read",
    "prescription.write",
    "lab.read",
    "imaging.read",
    "ipd.read",
    "queue.manage",
    "doctor.manage",
  ],
  DOCTOR: [
    "appointment.read",
    "patient.read",
    "clinical.read",
    "clinical.write",
    "prescription.read",
    "prescription.write",
    "lab.read",
    "lab.write",
    "imaging.read",
    "imaging.write",
    "ipd.read",
    "ipd.write",
    "emergency.read",
    "emergency.write",
    "queue.manage",
  ],
  NURSE: [
    "appointment.read",
    "patient.read",
    "clinical.read",
    "clinical.write",
    "nurse.manage",
    "ipd.read",
    "emergency.read",
    "emergency.triage",
    "queue.manage",
  ],
  RECEPTIONIST: [
    "appointment.read",
    "appointment.create",
    "appointment.update",
    "appointment.cancel",
    "appointment.checkin",
    "patient.read",
    "patient.update",
    "queue.manage",
    "emergency.read",
  ],
  LAB_TECHNICIAN: [
    "appointment.read",
    "patient.read",
    "lab.read",
    "lab.write",
  ],
  LAB_VERIFIER: [
    "appointment.read",
    "patient.read",
    "lab.read",
    "lab.write",
    "lab.verify",
  ],
  IMAGING_STAFF: [
    "appointment.read",
    "patient.read",
    "imaging.read",
    "imaging.write",
    "imaging.verify",
  ],
  PHARMACY_STAFF: [
    "prescription.read",
    "prescription.dispense",
    "patient.read",
    "billing.read",
  ],
  PHARMACY_MANAGER: [
    "prescription.read",
    "prescription.dispense",
    "pharmacy.stock",
    "pharmacy.purchase",
    "patient.read",
    "billing.read",
  ],
  BILLING_STAFF: [
    "billing.read",
    "billing.write",
    "appointment.read",
    "patient.read",
  ],
  FINANCE_MANAGER: [
    "billing.read",
    "billing.write",
    "finance.refund",
    "finance.reconcile",
    "appointment.read",
    "patient.read",
    "audit.read",
  ],
  HOUSEKEEPING_STAFF: [
    "housekeeping.complete",
    "bed.manage",
  ],
  MAINTENANCE_STAFF: [
    "maintenance.resolve",
  ],
  SECURITY_STAFF: [
    "appointment.read",
    "security.manage",
    "emergency.read",
  ],
  AMBULANCE_STAFF: [
    "ambulance.read",
    "ambulance.dispatch",
    "emergency.read",
  ],
  PATIENT: [
    "appointment.read",
    "appointment.create",
    "appointment.cancel",
    "patient.read",
    "patient.update",
    "prescription.read",
    "lab.read",
    "imaging.read",
    "billing.read",
    "caregiver.consent",
  ],
  ATTENDER: [
    "appointment.read",
    "patient.read",
    "billing.read",
  ],
  ATTENDER_CAREGIVER: [
    "appointment.read",
    "patient.read",
    "billing.read",
    "caregiver.consent",
  ],
};

export const ROLE_LABELS: Record<UserRole, string> = {
  SUPER_ADMIN: "Super Administrator",
  HOSPITAL_ADMIN: "Hospital Administrator",
  MEDICAL_DIRECTOR: "Medical Director",
  OPERATIONS_MANAGER: "Operations Manager",
  HR_MANAGER: "HR Manager",
  DEPARTMENT_HEAD: "Department Head",
  DOCTOR: "Consultant Physician",
  NURSE: "Staff Nurse",
  RECEPTIONIST: "Reception & Registration",
  LAB_TECHNICIAN: "Laboratory Technologist",
  LAB_VERIFIER: "Pathology Verification Specialist",
  IMAGING_STAFF: "Radiology Technologist / Radiologist",
  PHARMACY_STAFF: "Hospital Pharmacist",
  PHARMACY_MANAGER: "Pharmacy Inventory Manager",
  BILLING_STAFF: "Billing & Cashier Desk",
  FINANCE_MANAGER: "Finance & Accounts Manager",
  HOUSEKEEPING_STAFF: "Housekeeping & Sanitization",
  MAINTENANCE_STAFF: "Bio-Medical & Facility Maintenance",
  SECURITY_STAFF: "Campus Security & Safety",
  AMBULANCE_STAFF: "Emergency Ambulance Operations",
  PATIENT: "Patient",
  ATTENDER: "Caregiver / Attender",
  ATTENDER_CAREGIVER: "Authorized Caregiver / Attender",
};

export const ROLE_DASHBOARDS: Record<UserRole, string> = {
  SUPER_ADMIN: "/admin/dashboard",
  HOSPITAL_ADMIN: "/admin/dashboard",
  MEDICAL_DIRECTOR: "/admin/dashboard",
  OPERATIONS_MANAGER: "/admin/dashboard",
  HR_MANAGER: "/admin/dashboard",
  DEPARTMENT_HEAD: "/doctor/dashboard",
  DOCTOR: "/doctor/dashboard",
  NURSE: "/nurse/dashboard",
  RECEPTIONIST: "/reception/dashboard",
  LAB_TECHNICIAN: "/lab/dashboard",
  LAB_VERIFIER: "/lab/dashboard",
  IMAGING_STAFF: "/lab/dashboard",
  PHARMACY_STAFF: "/pharmacy/dashboard",
  PHARMACY_MANAGER: "/pharmacy/dashboard",
  BILLING_STAFF: "/billing/dashboard",
  FINANCE_MANAGER: "/billing/dashboard",
  HOUSEKEEPING_STAFF: "/nurse/dashboard",
  MAINTENANCE_STAFF: "/admin/dashboard",
  SECURITY_STAFF: "/security/dashboard",
  AMBULANCE_STAFF: "/security/dashboard",
  PATIENT: "/patient/dashboard",
  ATTENDER: "/patient/dashboard",
  ATTENDER_CAREGIVER: "/patient/dashboard",
};

export function hasPermission(role: UserRole | string, permission: Permission): boolean {
  const normalizedRole = role.toUpperCase() as UserRole;
  const permissions = ROLE_PERMISSIONS[normalizedRole];
  if (!permissions) return false;
  return permissions.includes(permission);
}

export function getRoleDashboard(role: UserRole | string): string {
  const normalizedRole = role.toUpperCase() as UserRole;
  return ROLE_DASHBOARDS[normalizedRole] || "/patient/dashboard";
}
