import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { FileText, ArrowLeft, AlertTriangle } from "lucide-react";
import { HOSPITAL_INFO } from "@/data/hospitalData";

export const metadata: Metadata = {
  title: "Terms and Conditions | Indo States Health",
  description:
    "Terms of service, clinical booking agreements, cancellation policies, and medical disclaimers for Indo States Health.",
};

export default function TermsPage() {
  return (
    <div className="bg-slate-50/60 min-h-screen pb-20">
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-3.5 flex items-center justify-between text-xs">
          <Link href="/" className="text-slate-600 hover:text-hospital-800 flex items-center gap-1.5 font-medium">
            <ArrowLeft className="w-3.5 h-3.5" /> Back to Home
          </Link>
          <span className="text-slate-400">Legal Agreement</span>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-3xl p-8 sm:p-12 border border-slate-200 shadow-sm space-y-8">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-hospital-50 text-hospital-700 text-xs font-semibold mb-3">
              <FileText className="w-3.5 h-3.5" /> Terms of Service
            </div>
            <h1 className="text-3xl font-extrabold text-slate-900 font-display mb-2">Terms and Conditions</h1>
            <p className="text-xs text-slate-500">Last Updated: October 2026</p>
          </div>

          <div className="space-y-6 text-xs text-slate-600 leading-relaxed">
            <section>
              <h2 className="text-base font-bold text-slate-900 mb-2">1. Acceptance of Terms</h2>
              <p>
                By accessing this website, scheduling appointments, utilizing our digital passes, or interacting with IndoCare AI, you agree to comply with and be bound by the following terms and conditions of Indo States Health.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-slate-900 mb-2">2. Medical Disclaimer (Informational Purpose Only)</h2>
              <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-950 mb-2">
                <strong>Crucial Clinical Notice:</strong> The content on this website and answers generated by IndoCare AI are for general educational and institutional guidance only. They do not constitute formal medical diagnoses, clinical prescriptions, or individualized physician-patient relationships. Always consult a qualified medical practitioner. In case of acute emergencies, contact our 24/7 hotline at {HOSPITAL_INFO.emergencyPhone} immediately.
              </div>
            </section>

            <section>
              <h2 className="text-base font-bold text-slate-900 mb-2">3. Appointments and Digital Passes</h2>
              <p>
                An online booking generates a unique digital reference code and pass. A confirmed digital pass reserves an operational slot with our clinical team. Patients are requested to arrive 15 minutes prior to their slot. Rescheduling or cancellation can be performed through the patient portal or by calling our scheduling desk at least 4 hours before the appointment time.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-slate-900 mb-2">4. Payment Policy</h2>
              <p>
                Indo States Health operates on an upfront, transparent pricing model. Diagnostic scans and health packages are payable on arrival at the hospital reception or via approved digital settlement counters. All printed invoices are computerized and compliant with statutory healthcare tax guidelines.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-slate-900 mb-2">5. Intellectual Property</h2>
              <p>
                All hospital trademarks, service marks, logo designs, clinical protocols, and educational articles are the proprietary property of Indo States Health and ARDOR Care Foundation.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-slate-900 mb-2">6. Governing Jurisdiction</h2>
              <p>
                These terms are governed by the laws of India. Any disputes arising out of the services rendered shall be subject to the exclusive jurisdiction of the competent courts in Coimbatore, Tamil Nadu.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
